### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3268: ordinal not in range(128)

### ISSUE THREAD

**Issue by wanghaisheng** [fmalina/PDFtranscript#6]
pdf file :[s5_100006_2008_06_09__1.pdf](https://github.com/fmalina/transcript/files/424726/s5_100006_2008_06_09__1.pdf)

run in docker 

```
#Dockerfile to build a pdf2htmlEx image

FROM ubuntu:15.10

#[wanghs@db2 debian]$ docker build -t dc/pdf2htmlex .
#[wanghs@db2 debian]$ docker run --rm --name pdf2htmlex-programming-demo -it -v $(pwd):/tmp dc/pdf2htmlex /bin/bash




ADD sources.list /etc/apt/sources.list

#
#Install git and all dependencies
#
RUN  apt-get -y update &&  apt-get install -qq git cmake autotools-dev libjpeg-dev libtiff5-dev libpng12-dev libgif-dev libxt-dev autoconf automake libtool bzip2 libxml2-dev libuninameslist-dev libspiro-dev libpango1.0-dev libcairo2-dev chrpath uuid-dev uthash-dev    python3.4   python3.4-dev python3-pip  libfreetype6 libqtcore4 libqtgui4 ttfautohint poppler-data libjpeg-dev 


#
#Clone the pdf2htmlEX fork of fontforge
#compile it
#
RUN git clone https://github.com/coolwanglu/fontforge.git fontforge.git
RUN cd fontforge.git && git checkout pdf2htmlEX && ./autogen.sh && ./configure && make V=1 &&  make install

#
#Install poppler utils
#
RUN  apt-get install -qq libpoppler-glib-dev libpoppler-private-dev

#
#Clone and install the pdf2htmlEX git repo



RUN  \
    cd /tmp \ 
    && apt-get install wget \
    && wget https://github.com/coolwanglu/pdf2htmlEX/archive/v0.14.6.tar.gz \
    && tar xvf v0.14.6.tar.gz \
    && cd pdf2htmlEX* 
RUN cd  /tmp/pdf2htmlEX*   &&  cmake . && make &&  make install



# install  transcript  
RUN apt-get install -y libxml2-dev libxslt1-dev

RUN  \
     cd /tmp \ 
     && git clone  https://github.com/fmalina/transcript \
    && cd transcript \
#    && pip3 install  -i https://pypi.tuna.tsinghua.edu.cn/simple lxml cssselect freetype-py
    && pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple  -r requirements.txt 

VOLUME /pdf
WORKDIR /pdf

CMD ["pdf2htmlEX"]

```

error like this 

```
root@85f8bef09062:/tmp/transcript# ./pdf2html.py
Preprocessing: 11/11
Working: 11/11

[None]
root@85f8bef09062:/tmp/transcript# ./transcript.py
Loading fonts from: ../ttf
FangSong Regular 28562 glyphs
/tmp/transcript/test-data/HTML/s5_100006_2008_06_09__1/s5_100006_2008_06_09__1.html
'ascii' codec can't decode byte 0xee in position 3046: ordinal not in range(128)
Traceback (most recent call last):
  File "./transcript.py", line 362, in batch_process
    semanticize(path)
  File "./transcript.py", line 251, in semanticize
    dom, dimensions = prepare(doc_path)
  File "./transcript.py", line 209, in prepare
    doc = s = open(doc_path).read()
  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xee in position 3046: ordinal not in range(128)

/tmp/transcript/test-data/HTML/3.x/3.x.html
'ascii' codec can't decode byte 0xe5 in position 817: ordinal not in range(128)
Traceback (most recent call last):
  File "./transcript.py", line 362, in batch_process
    semanticize(path)
  File "./transcript.py", line 251, in semanticize
    dom, dimensions = prepare(doc_path)
  File "./transcript.py", line 209, in prepare
    doc = s = open(doc_path).read()
  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 817: ordinal not in range(128)

/tmp/transcript/test-data/HTML/1/1.html
'ascii' codec can't decode byte 0xe5 in position 815: ordinal not in range(128)
Traceback (most recent call last):
  File "./transcript.py", line 362, in batch_process
    semanticize(path)
  File "./transcript.py", line 251, in semanticize
    dom, dimensions = prepare(doc_path)
  File "./transcript.py", line 209, in prepare
    doc = s = open(doc_path).read()
  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 815: ordinal not in range(128)

/tmp/transcript/test-data/HTML/2/2.html
'ascii' codec can't decode byte 0xe2 in position 3268: ordinal not in range(128)
Traceback (most recent call last):
  File "./transcript.py", line 362, in batch_process
    semanticize(path)
  File "./transcript.py", line 251, in semanticize
    dom, dimensions = prepare(doc_path)
  File "./transcript.py", line 209, in prepare
    doc = s = open(doc_path).read()
  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3268: ordinal not in range(128)

root@85f8bef09062:/tmp/transcript#
```

**Comment by wanghaisheng** [comment]
fix with  minor changes  "transcript.py"

```
#!/usr/bin/env python3
#-*-coding:utf-8-*- 
... (note: full source was pasted here)
```

**Comment by fmalina** [comment]
Please fork and send a pull request instead of copy-pasting code. Thank you.
